### ISSUE TITLE
A required step for newly configured servers

### ISSUE THREAD

**Issue by CooperMaxwell** [dellnoantechnp/brdgrd_with_SS#1]
First, thanks for the guide!

I've noticed that a newly deployed server need to install gcc, build-essentials and make before the compile step.

To install them, use these commands:(add sudo if needed)
apt install make
apt install gcc
apt update
apt install build-essentials

Please add them to help more ppl :)

**Comment by dellnoantechnp** [comment]
Ok，tks  :)
